Repository ChaosChain/chaoschain-launchpad, pull requests merged in 2025-04, with the labels that each got.

#96 feature/cometbft
  .gitignore
  ai/discussion.go
  api/handlers/handlers.go
  api/routes.go
  assets/abci.png
  assets/cometbft.png
  client/agent-launchpad/pnpm-lock.yaml
  cmd/agent/main.go
  cmd/main.go
  cmd/node/node.go
  config/config.go
  consensus/abci/application.go
  consensus/config/config.go
  core/agent.go
  core/cometbft.go
  core/database.go
  core/transaction.go
  core/tx.go
  examples/previous_presidents_of_united_states.json
  go.mod
  go.sum
  mempool/mempool.go
  registry/agent_registry.go
  registry/chain_registry.go
  registry/registry.go
  utils/helpers.go
  validator/social_registry.go
Labels: enhancement, dependencies, chore, go

#115 Add CI/CD pipeline with GitHub Actions, including Golang and NextJS c…
  .github/workflows/main.yml
  api/handlers/handlers.go
  client/agent-launchpad/package-lock.json
  client/agent-launchpad/package.json
  client/agent-launchpad/src/app/forum/[threadId]/page.tsx
  client/agent-launchpad/src/app/forum/page.tsx
  client/agent-launchpad/src/config/index.ts
  client/agent-launchpad/src/services/api.ts
  cmd/agent/main.go
  cmd/main.go
  communication/discussion_watcher.go
  communication/nats_messaging.go
  da_layer/eigenda_client.go
  da_layer/eigenda_service.go
  da_layer/eigenda_storage.go
  da_layer/generate_key.go
  go.mod
  p2p/p2p.go
  registry/agent_registry.go
  tests/test_forum.go
  tests/test_nats.go
Labels: documentation, security

#133 langgraph agent on fine tuned over ingesting all eips, prototypo ontology, eth book, eth eip issues, prs, discussions
  experiments/eips/agent_state.py
  experiments/eips/core_eips.jsonl
  experiments/eips/data/eip-ontology.txt
  experiments/eips/data/ethereum-glossary.txt
  experiments/eips/finetune.py
  experiments/eips/ingest_data.py
  experiments/eips/main.py
  experiments/eips/prepare_training_data.py
  experiments/eips/requirements.txt
Labels: documentation, research
