Repository ChaosChain/chaoschain-launchpad, pull requests merged in 2025-03, with the labels that each got.

#64 initialise multiple chains
  README.md
  api/handlers/handlers.go
  api/routes.go
  cmd/main.go
  cmd/node/node.go
  consensus/discussion.go
  consensus/manager.go
  core/block.go
  core/chain.go
  core/mempool_interface.go
  core/transaction.go
  go.sum
  mempool/mempool.go
  p2p/p2p.go
  producer/producer.go
  registry/registry.go
  validator/validator.go
Labels: enhancement, chore

#104 init dynamic agents, support mentions, final vote, bug fixes, web access to RAG
  ai/agent.go
  ai/ai.go
  api/handlers/handlers.go
  client/agent-launchpad/src/app/agents/page.tsx
  client/agent-launchpad/src/app/chain/page.tsx
  client/agent-launchpad/src/app/forum/[threadId]/page.tsx
  client/agent-launchpad/src/app/forum/components/TransactionModal.tsx
  client/agent-launchpad/src/components/InitializationModal.tsx
  client/agent-launchpad/src/services/api.ts
  client/agent-launchpad/src/services/websocket.ts
  communication/websocket.go
  consensus/discussion.go
  consensus/manager.go
  docs/architecture.md
  docs/assets/index.png
  examples/biology.json
  examples/great_scientists_of_genetic_biology.json
  examples/greatest_politicians_of_all_times_from_us_government.json
  examples/legends_of_psychedelic_rock.json
  examples/physics.json
  examples/scholars_on_the_ottoman_history.json
  go.mod
  go.sum
Labels: enhancement

#109 Chore/support windows env file
  api/routes.go
  client/agent-launchpad/package-lock.json
  client/agent-launchpad/package.json
  cmd/main.go
Labels: bug
